print("-------------------------------------------------------------------------------------------------------------------------------------------------")
print("Hoi ik ben Thom en ik ga je vandaag meenemen door een avontuur van een vluchteling, je mag zelf zijn pad beslissen en kijken waar hij dan uitkomt")
print("")
print("Dit verhaal gaat over George hij is 20 en woont in Engeland.")
print("Zijn leven was eerst redelijk normaal. Een gewoone jeugd gehad begonnen aan een studie een vriendin veel vrienden en christelijk.")
print("dus hij had een redelijk normaal leven totdat er op een bepaalde dag een dictator aan de macht kwam. De dictator was eerst niet zo slecht")
print("Hij zorgde goed voor het volk en begon veel projecten die de bevolking hielp, maar hij had wel een paar keer uitgesproken over het christelijke geloof")
print("door deze uitspraken vertrouwde George de dictator niet")

print("maar hij kon er in zijn eentje niet veel aan doen dus hij liet het maar zitten voor nu maar hij was wel op zijn hoede.")
print("na meerdere keren uitspraken te hebben tegen het geloof zat George te denken of de ditator misschien alleen nu het goed deed om de support van het volk te krijgen")
print("na een paar jaar bleek George gelijk te krijgen de dictator begon met het christelijk geloof te verbannen")
print("ondertussen had George al een vrouw en een kind van 2 hij zag dit al aankomen en had al wat plannen voorbereid hier op")
print("het vol was het niet eens met deze veranderingen maar de dictator zetten de politie en het leger in en verbood het geloof volledig")
print("redelijk snel begonnen de rellen en dook er een rebellen leger op")
print("George was ook christelijk en ging dus het rebellen leger maar hij wist niet hoe maar gelukkig weet een vriend het wel en wijst hem naar het leger")
print("")
print("dus via een vriend is hij de rebellen gejoined")
print("hij werd meteen overgeplaatst naar de rebellen stad van Exeter")
print("hij moest in veel gebouwen wonen die al in puin lagen veilig was het niet")
print("op het front moest hij ook een masker dragen om zijn identiteit te verbergen")
print("want anders zouden ze misschien zijn vrouw en kind iets aandoen die nog in London woonde om dat  het in exeter niet veilig was")
print("tijdens een gevecht was zijn masker afgevlogen en werd zijn gezicht gespot door een camera")
print("hij stuurde meteen zijn vrouw een bericht om te gaan onderduiken")
print("en George zelf moest vluchten maar hoe wist hij niet")
print("")
print("A. hij koos het vliegtuig om te vluchten naar Nederland")
print("B. hij koos om met een bootje te varen over het kanaal naar nederland")
print("")

aw = input("hij koos voor: ")
if (aw == "A"):
    print("")
    print("George koos er voor om het te wagen op een nep paspoort.")
    print("maar dit ging fout op het vliegveld is hij opgepakt voor een nep paspoort.")
    print("toen de politie zijn echte identiteit achterhaalde zij hebben hem toen direct in een gevangenis kamp gegooid")
    print("in dit kamp waren de omstandig heden erg slecht")
    print("iedereen zat ik klein tentjes die half in elkaar storten")
    print("de grond wat vroeger een groot gras veld was was nu een modder boel")
    print("er was maar 1 toilet gebouw voor het hele kamp er stonden op elk moment van de dag minstens 20 mensen in de rij")
    print("heel veel mensen zagen er ondervoed uit en of waren ziek")
    print("er waren zelfs kinderen in dit kamp de revolutie ging zo snel dat ze geen tijd hadden om aparte kampen te maken")
    print("George werd zelf ook in zo'n tentje gegooid het tentje had  een slaapzak die half onder de modder zat en een kussen")
    print("naast het kussen lag een opwindbaar zaklamp voor 's nachts, een bidon en een bord want bestek kon als wapen worden gebruikt")
    print("vanaf het eerste moment dat George in et kamp zat probeerde hij al een plan te maken om te ontsnappen maar hoe hij dat ging doen wist hij niet")
    print("wat hem opviel is dat er niet heel veel bewakers waren en dat ze vooral in torens zaten en op de muur zaten")
    print("tegerlijke tijd was hij bang of zij misschien ook zijn familie had of niet want hij wou niet weten wat de overheid hun aan zou doen")
    print("maar hij wou niet lang wachten om er achter te komen hij wou nu actie over ondernemen hij had twee plannen")
    print("")
    print("A. hij zou de scherven van zijn bord gebruiken voor een wapen daarmee zou hij een gevecht starten waardoor de bewakers op dat gebied focusde")
    print("waardoor hij tussen het gevecht we kon glippen en dan langs de tentjes over de muur kon klimmen want er zat geen prikkeldraad op")
    print("B. wat hem opviel is dat de bewakers een rondje zouden lopen om te checken of alles wel goed ging dus zijn plan was om dan een bewaker neer te halen")
    print("en om dan zijn bewakings kleren aan te doen en om dan het kamp uit te lopen")
    print("")

    aw = input("George kiest voor plan: ")

    if (aw == "A"):
        print("")
        print("hij ging meteen aan de slag omdat het al nacht was en dan was het makkelijker om weg te rennen")
        print("hij sloeg met zijn hand het bord kapot en pakte een scherpe scherf dit zou hij gebruiken")
        print("hij gooide een andere scherf tegen iemand aan waarvan hij wist dat die heel aggresief was")
        print("hij gooide meteen raak de grote sterke kerel stond meteen op en wou weten wie het deed")
        print("George wees meteen iemand aan die naast hem zat en de kerel liep meteen op die andere af")
        print("hier ontstond een gevecht en dat werd maar groter en groter. De bewakers zagen dit en rende er snel op af")
        print("George zag dat hij nu zijn kans moest pakken ")
        print("hij glipte ongemerkt tussen het gevecht door en begon te sluipen naar de muur hij ging van tent naar tent\n hij kwam ongezien bij de muur en begon met klimmen verassend genoeg werkte zijn plan hij werkt niet opgemerkt en kon weg rennen nu ging hij opzoek naar een boot om daarmee het kanaal overtesteken")
        print("na een paar uur kwam hij aan bij een kano verhuur bedrijf \n na eerst te kijken of iemand op aan het letten was stal hij snel een kano en rende hij weg nu hij een boot had kon hij het kanaal oversteken en liep hij richting de zee")
        print("toen hij aankwam bij een dorpje bij de kust liet hij zijn kano ergens in eens steegje liggen en liep hij een supermarkt in\n hij had geen geld dus hij stopte zo veel mogelijk eten en drinken in zijn jas en liep de winkel uit voor een of andere reden hield niemand hem tegen")
        print("terwijl hij het strand opliep zat hij weer te denken aan zijn vrouw en kind en waar die zijn en hoe het met hun gaat hij kon ze maar niet uit zijn hoofd krijgen\n denkend aan hun rende hij de zee in en begon hij met varen hij had niet de beste dag uitgekozen want het waaide nog wel wat maar het was niet alsof hij een keuze had")
        print("de eerste dag was redelijk ruig maar het lukte hem om een voor zijn gevoel een redelijk eind te pedelen\n op de tweede dag was de zee erg rustig en dat vond George wel kalmerend\n maar op de derde dag had hij geen energie meer en had overal kramp en pijn")
        print("de zee was die dag weer ruig maar hij zetten door\n na 4 dagen op zee te hebben gezeten kon hij land zien en dat was maar goed want zijn eten en drinken was bijna op en hij had overal pijn\n opeens uit het niks kreeg hij weer energie en begon hij met pedelen")
        print("na nog een paar uur pedelen was hij er nog niet maar hij werd door een zeilboot gespot\n de zeilboot had een nederlandse vlag en hielp hem heel vriendelijk\n de mensen op de boot zeiden dat hij in zeeland was en dat ze hem bij de polite af gingen leveren")
        print("George werd even bang en dacht dat de politie hem misschien meteen weer terug zouden sturen\n maar nee de politie hielp hem heel goed en stuurde hem meteen door naar een AZC ")
        print("van de politie had hij gehoord dat dit een verblijf is waar hij kan overnachten en kan wonen voor de komende tijd\n aangekomen bij de AZC werd hem verteld dat hij hier kon verblijven totdat hij te horen kreeg of hij mocht blijven of niet\n ondertussen mocht hij zoeken naar een baan hier in de buurt")
        print("hij kreeg twee keuzes voor baantjes hij: ")
        print("A. in een supermarkt gaan vakkenvullen")
        print("B. of hij kon bij een schoonmaak bedrijf werken")
        print("")
        aw = input("George koos er voor om te werken bij: ")
        if (aw == "A"):
            print("")
            print("hij werd al redelijk snel aangenomen want de supermarkt had speciaal plaatsen over voor vluchtelingen\n maar toch elke dag kon hij maar niet stoppen met denken aan zijn familie en had hij flashbacks naar de vreselijke tijd in het leger\n")
            print("na zijn eerste werk dag vroeg hij bij het AZC hoe hij zijn vrouw en kind ook hier naartoe kan laten komen, ze zeiden tegen hem dat dat hij erst moet wachten totdat hij hier mag blijven en dan kan hij er voor zorgen dat zijn vrouw en kind ook komen")
            print("dus voor hem was het nu afwachten en hopen dat hij mag blijven dit zou ongeveer tussen een paar weken tot een paar maanden duren\n dus hij moest maar wachten tot hij antwoord kreeg ")
            print("maar na een week konden zijn gedachtes nog steeds niet tot rust komen dus hij ging naar een therapeut toe om van die gedachtes af te komen en door de weken heen te komen\n en dan eidelijk na 2 maanden te hebben gewacht krijgt hij te horen dat hij mag blijven")
            print("toen hij dit hoorde kon hij niet meer stuk hij ging meteen naar de gemeente toe en kijken hoe hij zijn vrouw en kind over kon laten plaatsten naar Nederland\n en ook dat lukte het was de mooiste dag van zijn leven na een jaar kon hij eindelijk weer zijn vrouw en kind zien")
            print("zijn kind was zo erg gegroeid, en zijn vrouw kwam in tranen naar hem toe gerent\n nu het gezin herenigd te hebben moesten ze opzoek naar een huis want ze konden niet in de AZC blijven\n door zijn harde werk had George al een paar promoties gekregen")
            print("hierdoor had hij een laptop gekocht en ging hij opzoek naar een baan die hij kon doen met zijn opleiding software developer\n al snel vond hij er een en kon hij aan de slag\n met deze loon en kon hij zoeken naar een huurhuis")
            print("nu leeft George nog gelukkig met zijn vrouw en kind in Nederland, maar soms heeft hij nog nachtmerries over zijn daden die hij vericht heeft in de oorlog en over zijn vrienden die hij heeft verloren")
            print("-----------------------einde verhaal-----------------------")
        elif (aw == "B"):
            print("")
            print("hij werd al redelijk snel aangenomen want het schoonmaak bedrijf had speciaal plaatsen over voor vluchtelingen\n maar toch elke dag kon hij maar niet stoppen met denken aan zijn familie en had hij flashbacks naar de vreselijke tijd in het leger\n")
            print("na zijn eerste werk dag vroeg hij bij het AZC hoe hij zijn vrouw en kind ook hier naartoe kan laten komen, ze zeiden tegen hem dat dat hij erst moet wachten totdat hij hier mag blijven en dan kan hij er voor zorgen dat zijn vrouw en kind ook komen")
            print("dus voor hem was het nu afwachten en hopen dat hij mag blijven dit zou ongeveer tussen een paar weken tot een paar maanden duren\n dus hij moest maar wachten tot hij antwoord kreeg ")
            print("maar na een week konden zijn gedachtes nog steeds niet tot rust komen dus hij ging naar een therapeut toe om van die gedachtes af te komen en door de weken heen te komen\n en dan eidelijk na 2 maanden te hebben gewacht krijgt hij te horen dat hij mag blijven")
            print("toen hij dit hoorde kon hij niet meer stuk hij ging meteen naar de gemeente toe en kijken hoe hij zijn vrouw en kind over kon laten plaatsten naar Nederland\n en ook dat lukte het was de mooiste dag van zijn leven na een jaar kon hij eindelijk weer zijn vrouw en kind zien")
            print("zijn kind was zo erg gegroeid, en zijn vrouw kwam in tranen naar hem toe gerent\n nu het gezin herenigd te hebben moesten ze opzoek naar een huis want ze konden niet in de AZC blijven\n door zijn harde werk had George al een paar promoties gekregen")
            print("hierdoor had hij een laptop gekocht en ging hij opzoek naar een baan die hij kon doen met zijn opleiding software developer\n al snel vond hij er een en kon hij aan de slag\n met deze loon en kon hij zoeken naar een huurhuis")
            print("nu leeft George nog gelukkig met zijn vrouw en kind in Nederland, maar soms heeft hij nog nachtmerries over zijn daden die hij vericht heeft in de oorlog en over zijn vrienden die hij heeft verloren")
            print("-----------------------einde verhaal-----------------------")

    elif (aw == "B"):
        print("")
        print("George had het besloten hij ging proberen een bewaker neer te halen om dan zijn uniform te pakken en dan zo naar buiten te glippen\n na een paar uur te wachten zag hij aan het begin van de rij een bewaker beginnen aan de controle\n George maakte zich klaar voor zijn actie")
        print("na een paar minuten wachten liep de bewaker langs George greep hem bij zijn benen en haalde hem neer\n met een harde klap van zijn beker kreeg hij hem knockout\n de andere mensen keken hem verbaast aan terwijl hij het uniform aan deed")
        print("na dat hij eindelijk het unifrom aan had ging hij doen alsof hij het rondje afmaakte\n toen hij terug kwam bij de tent van de bewakers vroegen zij zich af waarom zijn rondje zo lang geduurt had\n George zij dat hij gevallen was en even zat te praten met de gevangenen")
        print("de andere bewakers geloofde dit niet helemaal en vroeg of hij zijn masker af wou doen\n NEE schreewe George en de bewakers keken hem geschokt aan en vroegen waarom niet? George zij dat hij een lelijke wond had gekregen op zijjn hoofd en dat hij nu meteen naar de dokter moest")
        print("de andere bewakers geloofde hem nog steeds niet en rukde de helm van zijn kop af en zagen dat het niet hun collega was maar een van de gevangenen, snel hielden ze hem al onder schot en arresteerde ze hem\n George werd meteen in een gevangenis gegooid, blijkbaar had hij de bewaker dood geslagen")
        print("daarvoor werd hij er voor 10 jaar ingegooid maar toen zij er achter kwamen dat hij heel veel mensen had gedood op het slachtveld lieten ze hem zitten voor levenslang\n hij heeft nooit meer iets van zijn familie gehoord, behalve 1 gerucht dat ze gevonden waren en dood geschoten waren")
        print("dit was het einde voor George hij kon nergens meer naartoe en ontsnappen was onmogelijk")
        print("-----------------------einde verhaal-----------------------")
        

elif (aw == "B"):
    print("met dit plan was wel 1 probleem en dat probleem was dat hij geen boot had om het kanaal mee overtesteken maar iemand in het rebellen leger had hem iets vertelt over een organisatie die mensen over zou varen naar Nederland\n dus George ging naar die persoon toe en vroeg hem hoe hij die organisatie kon contacteren")
    print("hij kreeg het nummer van de baas van de smokkelaars na een kort overleg hadden ze afgesproken dat ze over een paar dagen al de oversteek zouden maken naar Nederland\n hij heeft dit verhaal bij zijn officier neer gelegd en is uit het rebellen leger gestapt hij kreeg nog een paar dagen aan voedsel en drinken mee toen hij gedag zij")
    print("nu moest hij binnen een paar dagen een groot stuk reizen naar de afgesproken locatie deze reis was al zwaar met weinig slaap en veel paranoide\n op 1 moment werd hij aangsproken door 2 politie agenten heel even was hij bang dat hij gepakt werd maar het bleek dat hij iets had laten vallen")
    print("na een paar dagen kwam hij uitgeput aan bij de locatie en daar stonden ze al te wachten op hem met een klein ruberen boot vol met mensen misschien wel 50 man op een klein bootje\n maar George had dit al verwacht en ging snel in de boot zitten hij had nauwelijks ruimte maar het was beter dan nog 1 minuut in dit land blijven")
    print("na een paar uur kreeg hij heel veel kramp en moest hij wel anders gaan zitten maar dit ging moeilijk omdat iedereen heel dicht op elkaar zat\n maar dit kon hij wel doorstaan en na een dag of 3 op zee hebben gezeten kwam hij aan op de Nederlandse kust\n maar hij had een idee dat er iets mis was aan de smokkelaars")
    print("en hij had gelijk de smokkelaars leide hun naar een verlaten hutje en hielden hun onderschot, ze vroegen om het geld maar dat had iedereen allang gegeven maar de smokkelaars konden nauwelijks engels en verstonden hun niet\n George had nog wat geld bij zich dus hij besloot: ")
    print("")
    print("A. het geld aan de smokkelaars te geven")
    print("B. het geld niet aan de smokkelaars te geven")
    print("")
    aw = input("hij koos er voor om: ")

    if (aw == "A"):
        print("dus George besloot om heel langzaam naar zijn broekzak te grijpen en er 100 euro uit te pakken\n dit was genoeg om hem vrij te laten gaan en hij werd door hun vrij gelaten maar de andere mensen zaten nog vast daar maar daar kon George niks aan doen\n nu ging George onderweg naar een dorp die in de buurt was")
        print("toen George in het dorp aan kwam wist hij niet wat hij moest doen moest hij naar de politie moest hij naar de gemeente hij wist het niet dus ging hij maar rond vragen op straat volgens mensen op straat kon hij het best naar de gemeente gaan\n dus dat deed hij eenmaal angekomen bij de gemeente vroegen zij om zijn naam en leeftijd")
        print("daarna werd er meteen een pasfoto gemaakt en werd hij naar een AZC doorgestuurd\n daar werd aan hem verteld dat hij ongeveer een maand moest wachten totdat hij te horen kreeg of hij mocht blijven in Nederland of niet\n om die tijd te doden en om zij gedachten van zijn familie af te houden werd hem aangeboden om een baan te nemen")
        print("maar hij weet niet of hij dat zo graag wou zo erg zou het otch niet zijn om een maandje te wachten dus hij kreeg een keuze: ")
        print("")
        print("A. wel te werken")
        print("B. niet te werken")
        print("")
        aw = input("zijn keuze was om: ")
        if (aw == "A"):
            print("George koos er voor om toch nog maar wel te gaan werken zelf wist hij niet waar hij kon gaan werken dus hij ging rond vragen bij de AZC")
            print("en daar kreeg hij te horen dat er nog een paar plekken zijn om te werken bij: ")
            print("")
            print("A. krantenwijk")
            print("B. bouwmarkt")
            print("")
            aw = input("hij koos voor: ")
            if(aw == "A"):
                print("dus George koos ervoor om een elke dag een krantenwijk te doen van het bedrijf kreeg hij een fiets waarmee hij het kon doen\n dit was maar goed want dan kon hij zijn gedachten van zijn gezin af houden\n maar uiteindelijk ging hij wel langs de gemeente om te vragen hoe hij zijn familie over kon plaatsen naar Nederland")
                print("dit kon maar hij moest wel eerst in Nederland mogen blijven\n en gelukkig na een maand wachten was dat ook zo hij kreeg te horen dat hij in Nederland mocht blijven wonen\n blijer dan dit kon hij niet zijn hij sprinten na zijn werk zo snel mogelijk naar het gemeente huis")
                print("daar vroeg hij meteen aan of hij zijn gezin hier over mocht vliegen\n en ook na een week lukte dat\n het moment dat hij na 1 jaar weer zijn vrouw en kind kon zien was het mooiste moment in zijn leven")
                print("nu hij legaal in Nederland mocht blijven mag hij ook een huis kopen want lang met zijn vrouw en kind in het AZC blijven wonen had hij ook geen zin in\n met het geld van zijn baan kocht hij een laptop om meteen opzoek te gaan naar een beter baan die hij kan doen met zijn opleiding")
                print("al redelijk snel had hij die gevonden en kon hij aan de slag\n met deze loon kon hij een huis huren en maakte hij plannen om een huis te kopen\n wat hij wel wist is dat hij hier in Nederland nog lang en gelukkig kan leven met zijn vrouw en kind")
                print("-----------------------einde verhaal-----------------------")
            elif(aw == "B"):
                print("dus George koos ervoor om in de bouwmarkt te gaan werken\n dit was maar goed want dan kon hij zijn gedachten van zijn gezin af houden\n maar uiteindelijk ging hij wel langs de gemeente om te vragen hoe hij zijn familie over kon plaatsen naar Nederland")
                print("dit kon maar hij moest wel eerst in Nederland mogen blijven\n en gelukkig na een maand wachten was dat ook zo hij kreeg te horen dat hij in Nederland mocht blijven wonen\n blijer dan dit kon hij niet zijn hij sprinten na zijn werk zo snel mogelijk naar het gemeente huis")
                print("daar vroeg hij meteen aan of hij zijn gezin hier over mocht vliegen\n en ook na een week lukte dat\n het moment dat hij na 1 jaar weer zijn vrouw en kind kon zien was het mooiste moment in zijn leven")
                print("nu hij legaal in Nederland mocht blijven mag hij ook een huis kopen want lang met zijn vrouw en kind in het AZC blijven wonen had hij ook geen zin in\n met het geld van zijn baan kocht hij een laptop om meteen opzoek te gaan naar een beter baan die hij kan doen met zijn opleiding")
                print("al redelijk snel had hij die gevonden en kon hij aan de slag\n met deze loon kon hij een huis huren en maakte hij plannen om een huis te kopen\n wat hij wel wist is dat hij hier in Nederland nog lang en gelukkig kan leven met zijn vrouw en kind")
                print("-----------------------einde verhaal-----------------------")
        elif (aw == "B"): 
            print("Hij besloot er voor om niet te gaan werken want hij vond een maand niks doen wel fijn\n dit bleek een hele verkeerde keuze te zijn hij begon zich te vervelen en kon aan niks anders denken dan zijn gezin\n hij ging langs bij de gemeente om er achter te komen hoe hij zijn familie hier naartoe kon halen")
            print("ze zeiden dat hij ze hier naartoe kon halen als hij hier legaal mocht blijven\n dus George moest nog een maand wachten tot hij zijn gezin hier naartoe kon halen\n door zijn veel vrije tijd kon hij nog steeds zijn gedachtes niet van zijn gezin afhalen")
            print("ook krijgt hij flashbacks van de horror waar hij doorheen is gegaan doordat hij in het rebellen leger zat\n George wist na een week dat hij hier iets aan moest doen")
            print("hij had twee keuzes: ")
            print("")
            print("A. toch te gaan werken")
            print("B. vrienden zoeken")
            print("")
            aw = input("zijn keuze was om: ")
            if(aw == "A"):
                print("George ging opzoek naar werk en ging tergelijke tijd ook naar een therapeut om hem the helpen met zij PTSD\n voor een baan had hij 2 keuzes hij kon kiezen uit: ")
                print("")
                print("A. krantenwijk")
                print("B. bouwmarkt")
                print("")
                aw = input("hij koos voor: ")
                if(aw == "A"):
                    print("dus George koos ervoor om een elke dag een krantenwijk te doen van het bedrijf kreeg hij een fiets waarmee hij het kon doen\n dit was maar goed want dan kon hij zijn gedachten van zijn gezin af houden\n maar uiteindelijk ging hij wel langs de gemeente om te vragen hoe hij zijn familie over kon plaatsen naar Nederland")
                    print("dit kon maar hij moest wel eerst in Nederland mogen blijven\n en gelukkig na een maand wachten was dat ook zo hij kreeg te horen dat hij in Nederland mocht blijven wonen\n blijer dan dit kon hij niet zijn hij sprinten na zijn werk zo snel mogelijk naar het gemeente huis")
                    print("daar vroeg hij meteen aan of hij zijn gezin hier over mocht vliegen\n en ook na een week lukte dat\n het moment dat hij na 1 jaar weer zijn vrouw en kind kon zien was het mooiste moment in zijn leven")
                    print("nu hij legaal in Nederland mocht blijven mag hij ook een huis kopen want lang met zijn vrouw en kind in het AZC blijven wonen had hij ook geen zin in\n met het geld van zijn baan kocht hij een laptop om meteen opzoek te gaan naar een beter baan die hij kan doen met zijn opleiding")
                    print("al redelijk snel had hij die gevonden en kon hij aan de slag\n met deze loon kon hij een huis huren en maakte hij plannen om een huis te kopen\n wat hij wel wist is dat hij hier in Nederland nog lang en gelukkig kan leven met zijn vrouw en kind")
                    print("-----------------------einde verhaal-----------------------")
                elif(aw == "B"):
                    print("dus George koos ervoor om in de bouwmarkt te gaan werken\n dit was maar goed want dan kon hij zijn gedachten van zijn gezin af houden\n maar uiteindelijk ging hij wel langs de gemeente om te vragen hoe hij zijn familie over kon plaatsen naar Nederland")
                    print("dit kon maar hij moest wel eerst in Nederland mogen blijven\n en gelukkig na een maand wachten was dat ook zo hij kreeg te horen dat hij in Nederland mocht blijven wonen\n blijer dan dit kon hij niet zijn hij sprinten na zijn werk zo snel mogelijk naar het gemeente huis")
                    print("daar vroeg hij meteen aan of hij zijn gezin hier over mocht vliegen\n en ook na een week lukte dat\n het moment dat hij na 1 jaar weer zijn vrouw en kind kon zien was het mooiste moment in zijn leven")
                    print("nu hij legaal in Nederland mocht blijven mag hij ook een huis kopen want lang met zijn vrouw en kind in het AZC blijven wonen had hij ook geen zin in\n met het geld van zijn baan kocht hij een laptop om meteen opzoek te gaan naar een beter baan die hij kan doen met zijn opleiding")
                    print("al redelijk snel had hij die gevonden en kon hij aan de slag\n met deze loon kon hij een huis huren en maakte hij plannen om een huis te kopen\n wat hij wel wist is dat hij hier in Nederland nog lang en gelukkig kan leven met zijn vrouw en kind")
                    print("-----------------------einde verhaal-----------------------")
            elif(aw == "B"):
                print("om zijn gedachtes van zijn gezin af te halen ging hij maar wat vrienden zoeken dit deed hij door met mensen te gaan praten\nal snel vond hij mensen waar hij goed mee kon praten en begon hij met afpsreken met die mensen\n al snel kwam hij er achter dat zij niet zo erg van de regeltjes hielden")
                print("ze hielden er van om te smoken George vond dat niet zo nice maar omdat hij niet zijn vrienden kwijt wou raken ging hij er toch in mee\n langszaam aan ging dit van wiet naar wiet en sterke drank\n op 1 dag was hij zoals gewoonlijk met zijn vrineden aan het smoken en aan het drinken en dan komt 1 iemand aan lopen met cocaine")
                print("iedereen vroeg zich af waar hij het vandaan had gehaald, maar die vriend wou het niet vertellen\n na heel lang te twijfel besloten ze het om het te doen 1 voor een deden ze een klein lijntje\n eerst voelde hij niks maar na een half uur voelde hij het wel voor een of andere reden dachten ze dat het een goed idee was om en overval te plegen")
                print("half na denkend zat George erg te twijvelen want hij kan het geld wel goed gebruiken")
                print("dus hij koos voor: ")
                print("")
                print("A. mee doen")
                print("B. niet mee doen")
                print("")
                aw = input("zijn keuze was: ")
                if(aw == "A"):
                    print("George besloot om toch wel mee te doen met hun want hij was bang zijn vrienden kwijt te raken\n ze besloten om iemand die over straat liep te gaan bedrijgen met een mes en om geld te vragen\n ze deden allemaal een zak op hun hoofd en lipen naar iemand toe")
                    print("eerst ging het goed en de persoon die ze aan het overvallen waren gaf snel zijn geld\n maar wat ze niet door hadden is dat er net een politie auto langs reed\n ze werden snel gepakt en gearresteerd\n door de rechter werd besloten dat George niet mocht blijven in Nederland vanwegen slecht gedrag")
                    print("hij werd al snel terug gestuurd naar Engeland waar hij werd opgewacht door de politie\n hij werd daar in de cel gegooid en veroordeeld voor zijn tijd in het rebellen leger en voor de acties die hij daar heeft ondernomen\nze hadden hem levenslang gegeven hij kon niks meer doen hij was verslagen")
                    print("hij wist niet wat er met zijn familie is gebeurt en had een mental breakdown")
                    print("-----------------------einde verhaal-----------------------")
                elif(aw == "B"):
                    print("hij koos er voor om weg te lopen van het groepje en niet mee te doen aan de overval\n dat bleek maar goed want later bleek dat zij opgepakt waren door de politie\n George wist nog steeds niet wat hij moest doen")
                    print("")
                    print("A. of toch echt wel werk zoeken")
                    print("B. of de maand alleen afwachten")
                    print("")
                    aw = input("hij koos voor: ")
                    if(aw == "A"):
                        print("hij besloot wel echt werk te zoek\n hij kon nog bij de supermarkt werken hierdoor kon hij zijn gedachten van zijn gezin af houden\n na een maand mocht hij legaal blijven in Nederland\n hij zorgde er zo snel mogelijk voor dat zijn gezin over geplaatst werd")
                        print("de eerste keer dat hij weer zijn vrouw en kind zag na een jaar was het mooiste moment van zijn leven\n na dat ze in Nederland waren aan gekomen ging George meteen kijken voor een beter baan\n die vond hij en kon met die loon een huurhuis huren")
                        print("waar hij nu nog gelukkig met zijn vrouw en kind woont")
                        ("-----------------------einde verhaal-----------------------")
                    elif(aw == "B"):
                        print("hij wou alsnog niet werken en besloot om de maan maar in zijn eentje af te wachten dit was de langste maan d van zijn leven\n maar na een maand kreeg hij te horen dat hij mocht blijven\n hij rende gelijk naar het gemeente huis om zijn vrouw en kind over te laten vliegen")
                        print("het moment dat hij zijn vrouw en kind weer na een jaar zag was het moeiste moment van zijn leven\nmaar omdat hij nog niet gewerkt had was het moeilijk om voor hun te zorgen\n dus hij zocht meteen een goede baan na dat hij die gevonden had kon hij met de loon een huur huis betalen")
                        print("daar leeft hij nu nog steeds gelukkig met zijn vrouw en kind")
                        ("-----------------------einde verhaal-----------------------")
                        

    elif(aw == "B"):
        print("hij wou het geld niet aan de smokkelaars geven omdat hij het geld nog wou bewaren voor later\n dit bleek geen goeie actie te zijn want de smokkelaars begonnen met geluidsdempers op hun wapens te zetten")
        print("George had te lang gewacht hij werd vast gebonden en in de achterkant van een busje gegooid in het busje kon je niks van de buiten wereld zien\n de mensen waren in paniek ze wisten niet waar ze naartoe gingen en begonnen te schreewen")
        print("de smokkelaars bedreigde hun dat als ze niet stopte met schreewen dat ze dan iets aan gedaan werd\nGeorge wist niet wat er gebeurde en was ook heel bang voor zijn leven\n na een tijd stonden ze opeens stil en werden ze uit het busje gerukt")
        print("ze waren in het bos en er stond een nieuwe man tussen de groep deze man sprak wel engels en vroeg waar het geld was\n George legde uit dat het rebellen leger voor hem had betaald en dat hij dus niet hier hoorde te zijn")
        print("de mannen lietnen hem vrij maar zeiden dat als hij iets hier over zegt tegen iemand dat er iets met hem gebeurt\n heel geschroken liep George het door in mensen zagen hem en vroegen hem of het goed ging\nhij zij van wel maar ze gloofde hem niet en leverde hem af bij het politie bureau")
        print("eenmaal bij het bureau vroegen zij hem wat er was gebeurt\n George zij: ")
        print("")
        print("A. niks over de smokkelaars")
        print("B. alles over de smokkelaars")
        print("")
        aw = input("hij zij: ")
        if(aw == "A"):
            print("George zij niks over de smokkelaars want hij was bang dat ze hem iets aan deden\nhij werd doorgestuurd naar een AZC\n daar kreeg hij de optie om te gaan werken terwijl hij wachten op zijn antwoord of hij mocht blijven of niet")
            print("George had 2 keuzes voor werk")
            print("")
            print("A. supermarkt")
            print("B. bouwmarkt")
            print("")
            aw = input("hij koos voor: ")
            if(aw == "A"):
                print("hij had besloten om bij een supermarkt te werken dit hielp om zijn gedachtes van zijn familie af te houden\n na een maand werken kreeg hij te horen dat hij mocht blijven\n hij zorgde er zo snel mogelijk voor dat hij zijn gezin over mocht vliegen")
                print("het moment dat hij zijn vrouw en kind weer zag was het mooiste moment van zijn leven\nhij ging meteen een betere baan zoeken\n met de loon van die baan ging hij een huurhuis huren\nnu woont hij nog gelukkig met zijn vrouw en kind in zijn huurhuis")
                print("-----------------------einde verhaal-----------------------")
            elif(aw == "B"):
                print("hij had besloten om bij een bouwmarkt te werken dit hielp om zijn gedachtes van zijn familie af te houden\n na een maand werken kreeg hij te horen dat hij mocht blijven\n hij zorgde er zo snel mogelijk voor dat hij zijn gezin over mocht vliegen")
                print("het moment dat hij zijn vrouw en kind weer zag was het mooiste moment van zijn leven\nhij ging meteen een betere baan zoeken\n met de loon van die baan ging hij een huurhuis huren\nnu woont hij nog gelukkig met zijn vrouw en kind in zijn huurhuis")
                print("-----------------------einde verhaal-----------------------")
        elif(aw == "B"):
            print("George vertelde zijn hele verhaal vanaf het moment dat hij de smokkelaars zag met veel detail en beschrijving van hun gezichten\n na een uur alles te omschrijven zeiden ze dat ze genoeg hadden en stuurde hem naar het AZC\n daar kreeg hij een kamer en kreeg hij keuze tussen 2 baantjes om de tijd te doden")
            print("hij kon kiezen uit: ")
            print("")
            print("A. supermarkt")
            print("B. bouwmarkt")
            print("")
            aw = input("zijn keuze was: ")
            if(aw == "A"):
                print("hij had besloten om bij een supermarkt te werken dit hielp om zijn gedachtes van zijn familie af te houden\n paar dagen later kreeg hij te horen dat de smokkelaar op gepakt waren\n na een maand werken kreeg hij te horen dat hij mocht blijven\n hij zorgde er zo snel mogelijk voor dat hij zijn gezin over mocht vliegen")
                print("het moment dat hij zijn vrouw en kind weer zag was het mooiste moment van zijn leven\nhij ging meteen een betere baan zoeken\n met de loon van die baan ging hij een huurhuis huren\nnu woont hij nog gelukkig met zijn vrouw en kind in zijn huurhuis")
                print("-----------------------einde verhaal-----------------------")
            elif(aw == "B"):
                print("hij had besloten om bij een bouwmarkt te werken dit hielp om zijn gedachtes van zijn familie af te houden\npaar dagen later kreeg hij te horen dat de smokkelaar op gepakt waren\n na een maand werken kreeg hij te horen dat hij mocht blijven\n hij zorgde er zo snel mogelijk voor dat hij zijn gezin over mocht vliegen")
                print("het moment dat hij zijn vrouw en kind weer zag was het mooiste moment van zijn leven\nhij ging meteen een betere baan zoeken\n met de loon van die baan ging hij een huurhuis huren\nnu woont hij nog gelukkig met zijn vrouw en kind in zijn huurhuis")
                print("-----------------------einde verhaal-----------------------")
